# example slack plugin configuration TOML file
[teleport]
# Auth server address from `docker-compose.yml`
auth_server = "172.10.1.1:3025"                         

client_key = "/var/lib/teleport/plugins/slack/auth.key" # Teleport GRPC client secret key
client_crt = "/var/lib/teleport/plugins/slack/auth.crt" # Teleport GRPC client certificate
root_cas = "/var/lib/teleport/plugins/slack/auth.cas"   # Teleport cluster CA certs

[slack]
token = "api_token"             # Slack Bot OAuth token
secret = "signing-secret-value" # Slack API Signing Secret
channel = "channel-name"        # Slack Channel name to post requests to

[http]
listen_addr = ":8081" # Network address in format [addr]:port on which callback server listens, e.g. 0.0.0.0:443
public_addr = "example.com" # Hostname on which callback server is accessible externally
https_key_file = "/var/lib/teleport/plugins/slack/server.key"  # TLS private key
https_cert_file = "/var/lib/teleport/plugins/slack/server.crt" # TLS certificate

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/slack.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
